# Generated by Django 5.2.11 on 2026-03-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_contact_options_alter_contact_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=128, verbose_name='Full name')),
                ('full_name_en', models.CharField(max_length=128, null=True, verbose_name='Full name')),
                ('full_name_uz', models.CharField(max_length=128, null=True, verbose_name='Full name')),
                ('full_name_ru', models.CharField(max_length=128, null=True, verbose_name='Full name')),
                ('position', models.CharField(max_length=128, verbose_name='Position')),
                ('position_en', models.CharField(max_length=128, null=True, verbose_name='Position')),
                ('position_uz', models.CharField(max_length=128, null=True, verbose_name='Position')),
                ('position_ru', models.CharField(max_length=128, null=True, verbose_name='Position')),
                ('info', models.TextField(verbose_name='Info')),
                ('info_en', models.TextField(null=True, verbose_name='Info')),
                ('info_uz', models.TextField(null=True, verbose_name='Info')),
                ('info_ru', models.TextField(null=True, verbose_name='Info')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
            },
        ),
    ]
