# Generated by Django 5.2.11 on 2026-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_author_options_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='author',
            name='full_name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='author',
            name='professions_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Professions'),
        ),
        migrations.AddField(
            model_name='blog',
            name='long_description_ru',
            field=models.TextField(null=True, verbose_name='Long description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
    ]
