# Generated by Django 5.2.11 on 2026-03-04 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        # Remove old M2M (plain, no through) before creating the through model
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.CreateModel(
            name='ProductColorQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Stock quantity for this color', verbose_name='Quantity')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_quantities', to='products.productcolor', verbose_name='Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_quantities', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Color Quantity',
                'verbose_name_plural': 'Product Color Quantities',
                'db_table': 'product_color_quantity',
                'unique_together': {('product', 'color')},
            },
        ),
        # Add new M2M with through model
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductColorQuantity', to='products.productcolor', verbose_name='Colors'),
        ),
    ]
