# Generated by Django 5.2.11 on 2026-03-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_stock_productcolorquantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
    ]
