# Generated by Django 5.2.11 on 2026-03-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_depth_remove_product_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='country',
            field=models.CharField(blank=True, help_text='Country of origin', max_length=128, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='country_en',
            field=models.CharField(blank=True, help_text='Country of origin', max_length=128, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='country_ru',
            field=models.CharField(blank=True, help_text='Country of origin', max_length=128, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='country_uz',
            field=models.CharField(blank=True, help_text='Country of origin', max_length=128, null=True, verbose_name='Country'),
        ),
    ]
